// GALEX: Graphics Alex
//J.J. Gomez-Cadenas, December 2014


#include "RootGlobals.h"
#include "RootEve.h"
#include "RootGUI.h"
#include "RootUtil.h"

#include <alex/LogUtil.h>
#include <alex/ISvc.h>
#include <alex/PSvc.h>

#include "GalexMF.h"
#include "EveHits.h"
#include "MultiView.h"

#include <CLHEP/Units/SystemOfUnits.h>
#include "GalexInit.hh" // generated by gGonfigure


using namespace std;
using namespace CLHEP;
using namespace alex;

const char *filetypes[] = { "All files",     "*",
                            "ROOT files",    "*.root",
                            "NEXT files",    "*.next",
                            "ROOT macros",   "*.C",
                            0,               0 };


GalexMF::GalexMF(const TGWindow *p, UInt_t w, UInt_t h)
{

  fGalex= new TGMainFrame(p, w, h);
  fGalex -> SetWindowName("Galex GUI");

}

GalexMF::~GalexMF()
{
  fGalex->SetCleanup(kDeepCleanup);
  delete fEveTH;
  delete fEveTV;
  delete fEveTT;
  //delete fIrene;
}

void GalexMF::InitLogger()
{
  log4cpp::Appender *appender1 = new log4cpp::OstreamAppender("console", &std::cout);
  appender1->setLayout(new log4cpp::BasicLayout());

  log4cpp::Category& klog = log4cpp::Category::getRoot();
  klog.addAppender(appender1);
  klog.setPriority(log4cpp::Priority::DEBUG);

  klog.debug("In GalexMF::InitLogger(): \n");
  
}


void GalexMF::InitData()
{
  log4cpp::Category& klog = log4cpp::Category::getRoot();
  klog.debug("In GalexMF::InitData(): \n");
  klog.debug("In GalexMF::InitData() fCdirName = %s: \n", fCdirName.c_str());

  //fDirName = new TString(fCdirName);
  //fDirName = new TString("/Users/jjgomezcadenas/Development/NEXT/DATA");
  //string ff = "/Users/jjgomezcadenas/Development/NEXT/DATA";

  fDirName = new TString(fCdirName);
  fDeDx = fDeDx*keV;

  fRmin = fRmin*mm;
  fRmax = fRmax*mm;
  fZl = fZl*mm;

  klog.info("fDeDex (keV) = %7.2f: \n", fDeDx/keV);
  klog.info("fRmin (mm) = %7.2f fRmax (mm) = %7.2f fZl (mm) = %7.2f: \n", 
    fRmin/mm,fRmax/mm,fZl/mm);
  
  fTimer = new TStopwatch();
  fEvent=0;
  fFSet = false;
  fClose = true;

  // file info data

  sEvtTree = "EVENT";
  sEvtBranch = "EventBranch";

  //Init ISvc
  alex::ISvc::Instance().Init(fDebug);
  //Init PSvc
  InitPSvc();
  // Init Eve
  InitEve();
  
  
}

void GalexMF::InitPSvc()
{
  log4cpp::Category& klog = log4cpp::Category::getRoot();
  klog.debug("In GalexMF::InitPaolina(): \n");

  fMinDetX = fMinDetX*mm;
  fMaxDetX = fMaxDetX*mm;
  
  fMinDetY = fMinDetY*mm;
  fMaxDetY = fMaxDetY*mm;
  
  fMinDetZ = fMinDetZ*mm;
  fMaxDetZ = fMaxDetZ*mm;

  fXVoxel = fXVoxel*mm;
  fYVoxel = fYVoxel*mm;
  fZVoxel = fZVoxel*mm;

  fRBlob = fRBlob*mm;
  fVoxelDeDx = fDeDx* fZVoxel;

  klog << log4cpp::Priority::INFO << " Paolina::Detector X Size (mm) = " 
       << fMinDetX/mm << " , " << fMaxDetX/mm;
  klog << log4cpp::Priority::INFO << " Paolina::Detector Y Size (mm) = " 
       << fMinDetY/mm << " , " << fMaxDetY/mm;
  klog << log4cpp::Priority::INFO << " Paolina::Detector Z Size (mm) = " 
       << fMinDetZ/mm << " , " << fMaxDetZ/mm;

  klog << log4cpp::Priority::INFO << " Paolina::Voxel Size (mm) = " << 
          fXVoxel/mm << " , " << fYVoxel/mm << " , " << fZVoxel/mm;
  klog << log4cpp::Priority::INFO << " Paolina::Blob Radius (mm) = " << fRBlob/mm ;

  fVoxelSize.push_back(fXVoxel*mm);
  fVoxelSize.push_back(fYVoxel*mm);
  fVoxelSize.push_back(fZVoxel*mm); 
  
  std::pair<double,double> xRange;
  std::pair<double,double> yRange;
  std::pair<double,double> zRange;
  

  xRange.first  = fMinDetX;
  xRange.second = fMaxDetX;
  yRange.first  = fMinDetY;
  yRange.second = fMaxDetY;
  zRange.first  = fMinDetZ;
  zRange.second = fMaxDetZ;

  fDetSize.push_back(xRange);
  fDetSize.push_back(yRange);
  fDetSize.push_back(zRange);

  std::vector<double> left_range(3);
  std::vector<double> right_range(3);

  left_range[0]= fMinDetX;
  left_range[1]= fMinDetY;
  left_range[2]= fMinDetZ;

  right_range[0]= fMaxDetX;
  right_range[1]= fMaxDetY;
  right_range[2]= fMaxDetZ;

  // Init Svc
  PSvc::Instance().Init(fDebug,fDetSize);

}
void GalexMF::InitEve()
{
  fMarkerSize = 0.5;
  fEveTH = new EveHits(); //TH or TrueHits Eve Object
  fEveTV = new EveHits(); //TV or TrueVertex Eve Object
  fEveTT = new EveHits(); //TT or TrueTracks Eve Object

  fEvePV = new EveHits(); //PV Paolina Voxel Eve Object
  

  fEveTH->SetType("True hits");
  fEveTV->SetType("True vertex");
  fEveTT->SetType("True tracks");

  fEvePV->SetType("Paolina Voxels");

  int marker_color=3;
  int marker_style=4;
  double marker_size=fMarkerSize;
  
  fEveTH->SetMarkers(marker_color, marker_style, marker_size);

  int n_ebin = 10;
  double emin = 0; // in keV
  double emax = fDeDx; // in keV

  fEveTH->SetEnergyBins(n_ebin, emin, emax);

  marker_style=21;
  marker_size=fMarkerSize*fZVoxel;
  
  emax = fVoxelDeDx; // in keV

  fEvePV->SetMarkers(marker_color, marker_style, marker_size);
  fEvePV->SetEnergyBins(n_ebin, emin, emax);

  marker_color=46;
  marker_style=20;
  marker_size=2.0;
  
  fEveTV->SetMarkers(marker_color, marker_style, marker_size);

  fEveTH->SetStatus(false);
  fEveTV->SetStatus(false);
  fEveTT->SetStatus(false);
  fEvePV->SetStatus(false);
}
void GalexMF::SetLogger()
{
  log4cpp::Category& klog = log4cpp::Category::getRoot();
  klog.debug("In GalexMF::SetLogger to %s: \n", fDebug);

  if(strncmp (fDebug,"FATAL",4)  ==0) 
    klog.setPriority(log4cpp::Priority::FATAL);
  else if (strncmp (fDebug,"ERROR",4)  ==0) 
    klog.setPriority(log4cpp::Priority::ERROR);
  else if (strncmp (fDebug,"WARN",4)  ==0) 
    klog.setPriority(log4cpp::Priority::WARN);
  else if (strncmp (fDebug,"NOTICE",4)  ==0) 
    klog.setPriority(log4cpp::Priority::NOTICE);
  else if (strncmp (fDebug,"INFO",4)  ==0) 
    klog.setPriority(log4cpp::Priority::INFO);
  else if (strncmp (fDebug,"DEBUG",4)  ==0) 
    klog.setPriority(log4cpp::Priority::DEBUG);
}



void GalexMF::CleanGraphics()
{
  log4cpp::Category& klog = log4cpp::Category::getRoot();
  klog.debug("In GalexMF::CleanGraphics\n");
    
  if (fEveTH->Status())
  {
    klog.debug("Destroy gTrueHits from previous event\n");

    gTrueHits->DestroyElements();
    delete gTrueHits;
    fEveTH->SetStatus(false);
  }

  if (fEveTV->Status())
  {
    klog.debug("Destroy gTrueVertex from previous event\n");

    gTrueVertex->DestroyElements();
    delete gTrueVertex;
    fEveTV->SetStatus(false);
  }

  klog.debug("Destroy gTrueTracks from previous event\n");

  if (fEveTT->Status())
  {
    for(size_t i=0; i < gTrueTracks.size(); i++ )
    {
      klog.debug("Destroy track number %lu\n",i );
      gTrueTracks.at(i)->DestroyElements();
      delete gTrueTracks.at(i);
    }
    gTrueTracks.clear();
  }

  if (fEvePV->Status())
  {
    klog.debug("Destroy gPaolinaVoxels from previous event\n");

    gPaolinaVoxels->DestroyElements();
    delete gPaolinaVoxels;
    fEvePV->SetStatus(false);
  }
}

 void GalexMF::CloseFile()
{
  log4cpp::Category& klog = log4cpp::Category::getRoot();
  klog.debug("In GalexMF::CloseFile(): cleaning previous graphics objects\n");

  if (fClose)
  {

    CleanGraphics();
    //delete gEve->GetCurrentEvent();
    gEve->AddEvent(new TEveEventManager("Event", "NEXT Event")) ; 
  
    //reset event number
    fEvent=0;
    fFile->Close();
    delete fIevt;

    fBOpenFile-> SetEnabled(kTRUE);
    fBLoadEvent-> SetEnabled(kFALSE);
    fBTrueTracks-> SetEnabled(kFALSE);
    fBTrueHits-> SetEnabled(kFALSE);
    fBTrueVertex-> SetEnabled(kFALSE);
    fClose = false;
  }
}

void GalexMF::OpenFile()
{
  log4cpp::Category& klog = log4cpp::Category::getRoot();
  klog.debug("In GalexMF::OpenFile(): cleaning previous graphics objects\n");
  klog.debug("searching files in directory: %s\n",fCdirName.c_str());

  fClose = true; 
  fEvent=0;

 
  //TG file dialog object to grab file and directory
  TGFileInfo fi;
  fi.fFileTypes = filetypes;
  fi.fIniDir    = StrDup(*fDirName);
  //strcpy (fi.fIniDir,"/Users/jjgomezcadenas/Development/NEXT/DATA");
  
  new TGFileDialog(gClient->GetRoot(), this->fGalex, kFDOpen, &fi);

  if (!fi.fFilename) // Cancel was clicked, selection was ignored (fi.fFilename is 0)
    return;

  klog.debug("TGFileInfo: file = %s (dir = %s)\n", fi.fFilename,fi.fIniDir);
  klog.debug("file: %s (dir: %s)\n", fi.fFilename,fi.fIniDir);

  //*fDirName = fi.fIniDir;
  //*fFileName = fi.fFilename;

  fDirName = new TString(fi.fIniDir);
  fFileName = new TString(fi.fFilename);

  //Opening file, accessing tree, recreating Irene event

  klog.debug("Opening DST file =%s\n",fFileName->Data());
  fFile = TFile::Open(fFileName->Data());

  klog.debug("Opening Tree\n");
  fEvtTree = dynamic_cast<TTree*>(fFile->Get(sEvtTree));

  klog.info("number of entries in Irene Tree = %lld\n",fEvtTree->GetEntries());

  klog.debug("Recreating Irene event\n");
  fIevt = new irene::Event();
  fEvtTree->SetBranchAddress(sEvtBranch, &fIevt);

  klog.debug("Irene DST opened successfuly and Irene event loaded from branch\n");

    //enable/disable buttoms
  fBLoadEvent-> SetEnabled(kTRUE);
  fBCloseFile-> SetEnabled(kTRUE);
  fBTrueTracks-> SetEnabled(kFALSE);
  fBTrueHits-> SetEnabled(kFALSE);
  fBTrueVertex-> SetEnabled(kFALSE);
  fBOpenFile-> SetEnabled(kFALSE);

}

void GalexMF::LoadEvent()
{
  log4cpp::Category& klog = log4cpp::Category::getRoot();
  klog.debug("In GalexMF::LoadEvent(): cleaning previous graphics objects\n");

  CleanGraphics();

  fBTrueTracks-> SetEnabled(kTRUE);
  fBTrueHits-> SetEnabled(kTRUE);
  fBTrueVertex-> SetEnabled(kTRUE);
  fBPVoxels-> SetEnabled(kTRUE);
  
  klog.debug("reading topo event = %d \n",fEvent);
  klog.debug("Adding event = %d \to graphics manager\n",fEvent);

  gEve->AddEvent(new TEveEventManager("Event", "NEXT Event")) ; 

  int nb = fEvtTree->GetEntry(fEvent);
  klog.debug("Mapping irene event: read %d bytes from tree\n",nb);
  alex::ISvc::Instance().LoadEvent(fIevt);
  alex::ISvc::Instance().SetEvtNum(fEvent);

  fEvent++;
}

void GalexMF::TrueHits()
{
  log4cpp::Category& klog = log4cpp::Category::getRoot();
  klog.debug("In GalexMF::TrueHits():: event = %d\n",fEvent-1);

  IHits trueHits = alex::ISvc::Instance().GetTrueHits();
  klog << log4cpp::Priority::INFO << " true hits = " << trueHits.size();

  // double tt = alex::PSvc::Instance().ComputePaolinaObjects(trueHits);
  // klog.info("Paolina objects computed in %7.1f seconds\n",tt);
  klog.debug("cleaning previous graphics objects\n");
  CleanGraphics();  

  klog.debug("--Create graphic object (gTrueHits) for true hits \n");

  gTrueHits = fEveTH->Hits(trueHits);

  klog.debug("Adding gtpcHists to the manager and drawing scene\n");

  gEve->AddElement(gTrueHits);
  DrawScene(); 
  fEveTH->SetStatus(true);
        
}

void GalexMF::TrueTracks()
{
  log4cpp::Category& klog = log4cpp::Category::getRoot();
  klog.debug("In GalexMF::TrueTracks():: event = %d\n",fEvent-1);
 
  klog.debug("cleaning previous graphics objects\n");
  CleanGraphics();

  int marker_style=4;
  double marker_size=0.5;
  int marker_color=2;
  
  klog.debug("--Loop over tracks and get the hits of each track  \n");

  std::vector<const irene::Track*> trueTracks = fIevt->Tracks();
  for (size_t i=0; i < trueTracks.size(); i++)
  {
    const irene::Track* itrk = trueTracks.at(i);
    const std::vector<std::pair<TLorentzVector,double> > ihits = itrk->GetHits();
    std::vector<TLorentzVector> trkPoints;

    for(size_t i=0; i<ihits.size(); i++)
    {
      trkPoints.push_back(ihits.at(i).first);
    }

    klog.debug("--Create a graphic object per each track and store into vector  \n");
    
    marker_color++;
    
    fEveTT->SetMarkers(marker_color, marker_style, marker_size);

    //allocate a new graphic object of type gtpcHits
    TEvePointSet* trkHits = fEveTT->TrackHits(trkPoints);

    gTrueTracks.push_back(trkHits);

    klog.debug("Adding trkHits from track %d to the manager and drawing scene\n",i);

    gEve->AddElement(trkHits);

  }
  DrawScene();
  fEveTT->SetStatus(true);
}

void GalexMF::TrueVertex()
{
  log4cpp::Category& klog = log4cpp::Category::getRoot();
  klog.debug("In GalexMF::TrueVertex():: event = %d\n",fEvent-1);

 klog.debug("--Clear previous true vertex \n");

  if (fEveTV->Status())
  {
    klog.debug("Destroy gTrueVertex from previous event\n");

    gTrueVertex->DestroyElements();
    delete gTrueVertex;
    fEveTV->SetStatus(false);
  }

  klog.debug("--Create graphic object (gTrueHits) for true hits \n");

  std::vector<TLorentzVector> vertex;
  vertex.push_back(alex::ISvc::Instance().TrueVertex());

  gTrueVertex = fEveTV->TrackHits(vertex);

  klog.debug("Adding gTrueVertex to the manager and drawing scene\n");

  gEve->AddElement(gTrueVertex);
  DrawScene(); 
  fEveTV->SetStatus(true);
        
}

void GalexMF::PaolinaVoxels()
{
  log4cpp::Category& klog = log4cpp::Category::getRoot();
  klog.debug("In GalexMF::PaolinaVoxels() event = %d\n",fEvent-1);

  klog.debug("cleaning previous graphics objects\n");
  CleanGraphics();  

  klog.debug("--Create graphic object (gPaolinaVoxels) for voxels d \n");

  gPaolinaVoxels = fEvePV->Hits(
    alex::PSvc::Instance().ComputePaolinaVoxels(alex::ISvc::Instance().GetTrueHits(),fVoxelSize));

  klog.debug("Adding gPaolinaVoxels to the manager and drawing scene\n");

  gEve->AddElement(gPaolinaVoxels);
  DrawScene(); 
  fEvePV->SetStatus(true);
  fBPTracks-> SetEnabled(kTRUE);

}
void GalexMF::PaolinaTracks()
{
  log4cpp::Category& klog = log4cpp::Category::getRoot();
  klog.debug("In GalexMF::PaolinaTracks() event = %d\n",fEvent-1);
}

void GalexMF::PaolinaBlobs()
{
  log4cpp::Category& klog = log4cpp::Category::getRoot();
  klog.debug("In GalexMF::PaolinaBlobs() event = %d\n",fEvent-1);
}

void GalexMF::DrawScene()
{
  log4cpp::Category& klog = log4cpp::Category::getRoot();
  klog.debug("In GalexMF::DrawScene():: event = %d\n",fEvent-1);
  
  gEve->GetViewers()->DeleteAnnotations();
  TEveElement* top = gEve->GetCurrentEvent();

  klog.debug("Destroy EventRphi \n");
  gMultiView->DestroyEventRPhi();

  klog.debug("Import EventRphi \n");
  gMultiView->ImportEventRPhi(top);

  klog.debug("Destroy EventRhoz \n");  
  gMultiView->DestroyEventRhoZ();

  klog.debug("Import EventRhoz \n");
  gMultiView->ImportEventRhoZ(top);

  klog.debug("ReDraw() \n");
  gEve->Redraw3D();
}


void GalexMF::InitGui()
{
  log4cpp::Category& klog = log4cpp::Category::getRoot();
  klog.debug("in GalexMF::InitGui(): define cframe\n");

  fGalex -> SetWindowName("Galex GUI");

  TGCompositeFrame *cframe = new TGCompositeFrame(fGalex, 170, 20, 
                                             kHorizontalFrame | kFixedWidth);

  fBOpenFile = new TGTextButton(cframe, "&OpenFile");
  cframe->AddFrame(fBOpenFile, new TGLayoutHints(kLHintsTop | kLHintsExpandX,
                                             3, 2, 2, 2));
  fBOpenFile-> Associate(fGalex);
  fBOpenFile-> Connect("Clicked()", "GalexMF", this, "OpenFile()");
  fBOpenFile-> SetEnabled(kTRUE);

  fBLoadEvent = new TGTextButton(cframe, "&LoadEvent");
  cframe->AddFrame(fBLoadEvent, new TGLayoutHints(kLHintsTop | kLHintsExpandX,
                                                  3, 2, 2, 2));

  fBLoadEvent-> Associate(fGalex);
  fBLoadEvent-> Connect("Clicked()", "GalexMF", this, "LoadEvent()");
  fBLoadEvent-> SetEnabled(kFALSE);

  
  klog.debug("in GalexMF::GalexGui(): define iframe\n");

  TGCompositeFrame *iframe = new TGCompositeFrame(fGalex, 170, 20, 
                                                  kHorizontalFrame | kFixedWidth);
  
  
  fBTrueTracks = new TGTextButton(iframe, "&TTracks");
  iframe->AddFrame(fBTrueTracks, new TGLayoutHints(kLHintsTop | kLHintsExpandX,
                                              3, 2, 2, 2));

  fBTrueTracks-> SetEnabled(kFALSE); 
  fBTrueTracks-> Associate(fGalex);
  fBTrueTracks-> Connect("Clicked()", "GalexMF", this, "TrueTracks()");

   
  fBTrueHits = new TGTextButton(iframe, "&THits");
  iframe->AddFrame(fBTrueHits, new TGLayoutHints(kLHintsTop | kLHintsExpandX,
                                             3, 2, 2, 2));
  fBTrueHits-> SetEnabled(kFALSE);
  fBTrueHits-> Associate(fGalex);
  fBTrueHits-> Connect("Clicked()", "GalexMF", this, "TrueHits()");

  fBTrueVertex = new TGTextButton(iframe, "&TVertex");
  iframe->AddFrame(fBTrueVertex, new TGLayoutHints(kLHintsTop | kLHintsExpandX,
                                             3, 2, 2, 2));
  fBTrueVertex-> SetEnabled(kFALSE);
  fBTrueVertex-> Associate(fGalex);
  fBTrueVertex-> Connect("Clicked()", "GalexMF", this, "TrueVertex()");

  
  TGCompositeFrame *cframe1 = new TGCompositeFrame(fGalex, 170, 20, 
                                                  kHorizontalFrame | kFixedWidth);

  
  TGCompositeFrame *pframe = new TGCompositeFrame(fGalex, 170, 20, 
                                                  kHorizontalFrame | kFixedWidth);
  
  
  fBPTracks = new TGTextButton(pframe, "&PTracks");
  pframe->AddFrame(fBPTracks, new TGLayoutHints(kLHintsTop | kLHintsExpandX,
                                              3, 2, 2, 2));

  fBPTracks-> SetEnabled(kFALSE); 
  fBPTracks-> Associate(fGalex);
  fBPTracks-> Connect("Clicked()", "GalexMF", this, "PaolinaTracks()");

   
  fBPVoxels = new TGTextButton(pframe, "&PVoxels");
  pframe->AddFrame(fBPVoxels, new TGLayoutHints(kLHintsTop | kLHintsExpandX,
                                             3, 2, 2, 2));
  fBPVoxels-> SetEnabled(kFALSE);
  fBPVoxels-> Associate(fGalex);
  fBPVoxels-> Connect("Clicked()", "GalexMF", this, "PaolinaVoxels()");

  fBPBlobs = new TGTextButton(pframe, "&PBlobs");
  pframe->AddFrame(fBPBlobs, new TGLayoutHints(kLHintsTop | kLHintsExpandX,
                                             3, 2, 2, 2));
  fBPBlobs-> SetEnabled(kFALSE);
  fBPBlobs-> Associate(fGalex);
  fBPBlobs-> Connect("Clicked()", "GalexMF", this, "PaolinaBlobs()");

   
  fBExit = new TGTextButton(cframe1, "&Exit");
  cframe1->AddFrame(fBExit, new TGLayoutHints(kLHintsTop | kLHintsExpandX,
                                             2, 2, 2, 2));

  fBExit -> SetCommand("gApplication -> Terminate()");

  fBCloseFile = new TGTextButton(cframe1, "&CloseFile");
  cframe1->AddFrame(fBCloseFile, new TGLayoutHints(kLHintsTop | kLHintsExpandX,
                                             2, 2, 2, 2));
  fBCloseFile-> Associate(fGalex);
  fBCloseFile-> Connect("Clicked()", "GalexMF", this, "CloseFile()");

  fBCloseFile-> SetEnabled(kFALSE); 
  
  fGalex -> AddFrame(cframe, new TGLayoutHints(kLHintsCenterX, 2, 2, 5, 1));
  fGalex -> AddFrame(iframe, new TGLayoutHints(kLHintsCenterX, 2, 2, 5, 1));
  fGalex -> AddFrame(pframe, new TGLayoutHints(kLHintsCenterX, 2, 2, 5, 1));
  
  fGalex -> AddFrame(cframe1, new TGLayoutHints(kLHintsCenterX, 2, 2, 5, 1));
  fGalex -> MapSubwindows();
  fGalex -> Resize(fGalex -> GetDefaultSize());
  fGalex -> MapWindow();

}


void GalexMF::InitGeometry()
{
  log4cpp::Category& klog = log4cpp::Category::getRoot();
  klog.debug("in GalexMF::InitGeometry(): init Geometry\n");

  fNextGeom = new TEveElementList("Geometry");

  klog.debug("Creating a tube\n");  
  

  klog.info("SetParam: Toy detector dimensions:: fRmin =%7.1f mm fRmax =%7.1f mm fzl =%7.1f mm  \n",
    fRmin/mm,fRmax/mm,fZl/mm);

  fToyGeometry = new TEveGeoShape("ToyTPC");

  fToyGeometry->SetShape(new TGeoTube(fRmin, fRmax, fZl));
  fToyGeometry->SetMainColor(kCyan);
  fToyGeometry->SetMainTransparency(90);

  klog.debug("Adding tube element to geometry\n"); 
  fNextGeom->AddElement(fToyGeometry);

  klog.debug("Adding geometry to Eve\n"); 
  gEve->AddGlobalElement(fNextGeom);


  //Multiview
  klog.debug("Creating multiview\n");    
  
  gMultiView = new MultiView();

  klog.debug("Importing views\n");
  gMultiView->ImportGeomRPhi(fNextGeom);
  gMultiView->ImportGeomRhoZ(fNextGeom);
  gEve->Redraw3D(kTRUE);
}

int main(int argc, char **argv)
{

  //  TROOT root("root","Panel");
  TApplication app("GalexMF",&argc, argv);

  TEveManager::Create();
  TEveBrowser* browser = gEve->GetBrowser();
  browser->StartEmbedding(TRootBrowser::kLeft);

  GalexMF* gmf = new GalexMF(gClient -> GetRoot(), 1000, 600);
  gmf->InitLogger();
  gmf->InitGalex();
  gmf->InitData();
  gmf->InitGeometry();
  gmf->InitGui(); 
  app.Run();
  return 0;

}
